# Site settings
title: 唐星宇的博客
email: Lavanille777@gmail.com
description: > #唐星宇的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Lavanille777.github.io" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: Lavanille777@gmail.com
github_username:  Lavanille777

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 唐星宇
  email: Lavanille777@gmail.com
  link: http://Lavanille777.github.io/
  weibo: #
  github: http://github.com/Lavanille777
title: 唐星宇的博客                             #自定义常量

# avatar头像及Favicon
avatar: https://avatars2.githubusercontent.com/u/28102324?v=4&u=711c9ef521bd5bb3be37e6936f0b6fdc007a1d68&s=400
#favicon:

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: //hm.baidu.com/hm.js?22d94317cfb9f9e0bb476228d9f79278

# disqus 设置
disqus:
  shortname: lavanille
